export default {
  'people_fields_to_query': [
    'Full_Name^100',
    'Full_Name_Concat_Match^100',
    'First_Name^10',
    'Middle_Name^10',
    'Initial',
    'Surname^100'
    // 'Home_Town^50',
    // 'Home_Country_Name^50',
    // 'Home_Country_ISO_Code^50',
    // 'UPU_Home_State_Name^100',
    // 'UPU_Home_State_Code^100',
    // 'UPU_Home_Street_Name^10',
    // 'Home_Full_Address^50',
    // 'Previous_Home_Full_Address_Match^50'
  ],
  'people_fields_to_return': [
    'Full_Name',
    'First_Name',
    'Surname',
    'Is_Sanctioned',
    'People_Primary_Key',
    'People_Primary_Key.bak',
    'Person_Type_Name',
    'Home_Full_Address_Match',
    'Home_Town',
    'Home_State',
    'Home_Country_Name',
    'UPU_Previous_Home_Address_Match_Result',
    'DOB',
    'Business_Full_Address',
    'Job_Title'
  ],
  'organisations_fields_to_query': [
    'Legal_Form^100',
    'IP_Description^100',
    // 'Operating_Country_ISO_Code^100',
    // 'Operating_Full_Address',
    // 'Operating_Post_Code',
    // 'Registered_Full_Address',
    // 'Registered_Post_Code',
    // 'Registered_Town',
    'Trade_Registration_Number^100',
    'Trading_As',
    'VAT_Number^100',
    'Company_Registration_Number',
    'Organization_Full_Name_Original^100',
    // 'Registered_Country_Name^100',
    // 'Registered_Country_ISO_Code^100',
    'Legal_Full_Name^100'
    // 'Operating_Country_Name^100'
  ],
  'organisations_fields_to_return': [
    'Organisation_Full_Name',
    'Legal_Full_Name',
    'Organisation_Type_Name',
    'Organisation_Primary_Key',
    'Organisation_Primary_Key.bak',
    'Is_Sanctioned',
    'Operating_Country_ISO_Code',
    'Operating_Full_Address',
    'Operating_Post_Code',
    'Registered_Full_Address',
    'Registered_Post_Code',
    'Registered_Town',
    'Registered_Country_Name',
    'Registered_Country_ISO_Code',
    'Operating_Country_Name',
    'Operating_Town',
    'Operating_County_Name',
    'UPU_Registered_Street_Name',
    'Organisation_Full_Name_Original',
    'Organisation_Full_Name_Match',
    'Organisation_Full_Name_Previous',
    'Trading_As',
    'Domicile_Full_Address',
    'Mailing_Full_Address',
    'DNB_Legal_Class_Code',
    'ENTITY_STATUS'
  ],
  instruments_fields_to_query: [
    'Instrument_Name',
    'Organisation_Full_Name'
  ],
  instruments_fields_to_return: [
    'Instrument_Primary_Key',
    'Instrument_Primary_Key.bak',
    'Instrument_Name',
    'Organisation_Full_Name'
  ],
  addresses_fields_to_query: [
    'Country_Name',
    'Street_Start_Number^90',
    'Full_Address^100',
    'Post_Code^90',
    'Street_Name^50',
    'Town_Name^50',
    'Country_ISO_Code'
  ],
  addresses_fields_to_return: [
    'Address_Key',
    'Country_Name',
    'Full_Address',
    'Post_Code',
    'Street_Start_Number',
    'Street_Name',
    'State_Name',
    'Town_Name',
    'Country_ISO_Code'
  ],
  listed_organisations_fields_to_query: [],
  listed_organisations_fields_to_return: [],
  listed_people_fields_to_query: [],
  listed_people_fields_to_return: [],
  listed_objects_fields_to_query: [],
  listed_objects_fields_to_return: [],
  listed_locations_fields_to_query: [],
  listed_locations_fields_to_return: []
}
